"use client";

import { Building2, CalendarDays, Check, LoaderCircle, Plus, Save, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import type React from "react";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { organizationApi, type Branch, type Holiday, type Organization, type WorkingDay } from "@/lib/api/organization";

type Tab = "overview" | "branches" | "schedule" | "holidays";
const tabs: { id: Tab; label: string }[] = [{ id: "overview", label: "Overview" }, { id: "branches", label: "Branches" }, { id: "schedule", label: "Schedules" }, { id: "holidays", label: "Holidays" }];
const week = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

export function OrganizationWorkspace() {
  const [tab, setTab] = useState<Tab>("overview");
  const [organization, setOrganization] = useState<Organization>(null);
  const [branches, setBranches] = useState<Branch[]>([]);
  const [holidays, setHolidays] = useState<Holiday[]>([]);
  const [selectedBranch, setSelectedBranch] = useState<string>("");
  const [days, setDays] = useState<WorkingDay[]>([]);
  const [name, setName] = useState("");
  const [code, setCode] = useState("");
  const [notice, setNotice] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [branchDraft, setBranchDraft] = useState<{ id?: string; name: string; code: string; address: string }>({ name: "", code: "", address: "" });

  async function load() {
    const [currentOrganization, currentBranches, currentHolidays] = await Promise.all([organizationApi.get(), organizationApi.branches(), organizationApi.holidays()]);
    setOrganization(currentOrganization); setBranches(currentBranches); setHolidays(currentHolidays); setSelectedBranch((current) => current || currentBranches[0]?.id || "");
    setName(currentOrganization?.name || ""); setCode(currentOrganization?.code || "");
  }
  useEffect(() => { void load().catch((cause) => setError(cause instanceof Error ? cause.message : "Could not load organization settings.")); }, []);
  useEffect(() => { if (selectedBranch) void organizationApi.workingDays(selectedBranch).then(setDays).catch(() => setError("Could not load this branch schedule.")); }, [selectedBranch]);

  async function saveOrganization() { if (!organization) return; setBusy(true); setError(null); try { await organizationApi.update({ id: organization.id, name, code }); setNotice("Organization details saved."); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save changes."); } finally { setBusy(false); } }
  async function saveDays() { if (!selectedBranch) return; setBusy(true); setError(null); try { await organizationApi.replaceWorkingDays({ branchId: selectedBranch, days }); setNotice("Working week saved."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save schedule."); } finally { setBusy(false); } }
  async function saveBranch(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(null); try { if (branchDraft.id) await organizationApi.updateBranch({ branchId: branchDraft.id, name: branchDraft.name, code: branchDraft.code, address: branchDraft.address }); else await organizationApi.createBranch({ name: branchDraft.name, code: branchDraft.code, address: branchDraft.address }); setNotice("Branch saved."); setBranchDraft({ name: "", code: "", address: "" }); await load(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save branch."); } finally { setBusy(false); } }
  async function addHoliday(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); try { await organizationApi.createHoliday({ name: String(form.get("name")), holidayDate: String(form.get("date")), branchId: String(form.get("branchId")) || null }); setNotice("Holiday added."); event.currentTarget.reset(); setHolidays(await organizationApi.holidays()); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not add holiday."); } finally { setBusy(false); } }
  async function deleteHoliday(id: string) { setBusy(true); try { await organizationApi.deleteHoliday(id); setHolidays(await organizationApi.holidays()); setNotice("Holiday removed."); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not remove holiday."); } finally { setBusy(false); } }

  if (!organization) return <div className="flex min-h-64 items-center justify-center"><LoaderCircle className="animate-spin text-primary" aria-label="Loading organization" /></div>;
  return <div className="mx-auto w-full max-w-5xl space-y-6">
    <div><p className="text-xs font-semibold text-muted-foreground">Workspace administration</p><h1 className="font-heading mt-1 text-2xl font-bold tracking-[-0.03em] text-strong">Organization settings</h1><p className="mt-2 text-sm text-muted-foreground">Manage the shared context that keeps attendance records consistent.</p></div>
    <div className="flex gap-1 overflow-x-auto border-b border-border" role="tablist" aria-label="Organization settings"><span className="sr-only">Settings sections</span>{tabs.map((item) => <button key={item.id} type="button" role="tab" aria-selected={tab === item.id} onClick={() => { setTab(item.id); setNotice(null); setError(null); }} className={`min-h-11 shrink-0 border-b-2 px-4 text-xs font-bold transition-colors ${tab === item.id ? "border-primary text-strong" : "border-transparent text-muted-foreground hover:text-strong"}`}>{item.label}</button>)}</div>
    {notice ? <div className="flex items-center gap-2 rounded-[11px] bg-success/8 px-4 py-3 text-sm text-success ring-1 ring-success/20"><Check className="size-4" />{notice}</div> : null}
    {error ? <div role="alert" className="rounded-[11px] bg-destructive/8 px-4 py-3 text-sm text-destructive ring-1 ring-destructive/20">{error}</div> : null}
    {tab === "overview" ? <section className="rounded-[18px] bg-card p-6 shadow-[var(--shadow-card)] ring-1 ring-border"><div className="mb-6 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[11px] bg-workflow/10 text-workflow"><Building2 className="size-5" /></span><div><h2 className="font-heading font-bold text-strong">Organization details</h2><p className="text-xs text-muted-foreground">Timezone is fixed to Africa/Addis_Ababa for this release.</p></div></div><div className="grid gap-4 sm:grid-cols-2"><label className="space-y-2 text-xs font-bold text-strong">Name<Input value={name} onChange={(event) => setName(event.target.value)} /></label><label className="space-y-2 text-xs font-bold text-strong">Code<Input pattern="[A-Za-z0-9-]{2,20}" value={code} onChange={(event) => setCode(event.target.value)} /></label></div><Button className="mt-5 h-10 rounded-[11px] font-bold" onClick={saveOrganization} disabled={busy}><Save className="size-4" />Save details</Button></section> : null}
    {tab === "branches" ? <section className="space-y-4"><form onSubmit={saveBranch} className="grid gap-3 rounded-[18px] bg-card p-5 shadow-[var(--shadow-card)] ring-1 ring-border sm:grid-cols-[1fr_9rem_1.5fr_auto] sm:items-end"><label className="space-y-2 text-xs font-bold text-strong">Name<Input required value={branchDraft.name} onChange={(event) => setBranchDraft({ ...branchDraft, name: event.target.value })} placeholder="Branch name" /></label><label className="space-y-2 text-xs font-bold text-strong">Code<Input required pattern="[A-Za-z0-9-]{2,20}" value={branchDraft.code} onChange={(event) => setBranchDraft({ ...branchDraft, code: event.target.value })} placeholder="HQ" /></label><label className="space-y-2 text-xs font-bold text-strong">Address<Input required value={branchDraft.address} onChange={(event) => setBranchDraft({ ...branchDraft, address: event.target.value })} placeholder="Street, city, country" /></label><Button type="submit" className="h-8 rounded-[9px] font-bold" disabled={busy}><Plus className="size-4" />{branchDraft.id ? "Save" : "Add"}</Button></form><div className="grid gap-4 md:grid-cols-2">{branches.map((branch) => <div key={branch.id} className="rounded-[18px] bg-card p-5 shadow-[var(--shadow-card)] ring-1 ring-border"><div className="flex items-start justify-between"><div><h2 className="font-heading font-bold text-strong">{branch.name}</h2><p className="mt-1 text-xs text-muted-foreground">{branch.code} · {branch.address}</p></div><span className="rounded-full bg-success/10 px-2 py-1 text-[0.6875rem] font-bold text-success">{branch.status}</span></div><div className="mt-5 flex gap-2"><Button variant="outline" className="h-9 rounded-[11px] text-xs" onClick={() => { setSelectedBranch(branch.id); setTab("schedule"); }}>Manage schedule</Button><Button variant="ghost" className="h-9 rounded-[11px] text-xs" onClick={() => setBranchDraft({ id: branch.id, name: branch.name, code: branch.code, address: branch.address })}>Edit</Button></div></div>)}</div></section> : null}
    {tab === "schedule" ? <section className="rounded-[18px] bg-card p-6 shadow-[var(--shadow-card)] ring-1 ring-border"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-heading font-bold text-strong">Working week</h2><p className="text-xs text-muted-foreground">Choose a branch and maintain its schedule.</p></div><select value={selectedBranch} onChange={(event) => setSelectedBranch(event.target.value)} className="h-10 rounded-[11px] border border-input bg-background px-3 text-xs font-semibold">{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></div><div className="space-y-2">{[...days].sort((a, b) => a.weekday - b.weekday).map((day) => <div key={day.id} className="grid items-center gap-3 rounded-[11px] bg-[var(--surface-subtle)] p-3 sm:grid-cols-[1fr_auto_8rem_8rem]"><label className="flex items-center gap-3 text-xs font-semibold text-strong"><input type="checkbox" checked={day.isWorkingDay} onChange={(event) => setDays((current) => current.map((item) => item.id === day.id ? { ...item, isWorkingDay: event.target.checked } : item))} className="size-4 accent-primary" />{week[day.weekday]}</label><span className="text-[0.6875rem] text-muted-foreground">{day.isWorkingDay ? "Working day" : "Closed"}</span><Input type="time" disabled={!day.isWorkingDay} value={day.openingTime || ""} onChange={(event) => setDays((current) => current.map((item) => item.id === day.id ? { ...item, openingTime: event.target.value } : item))} /><Input type="time" disabled={!day.isWorkingDay} value={day.closingTime || ""} onChange={(event) => setDays((current) => current.map((item) => item.id === day.id ? { ...item, closingTime: event.target.value } : item))} /></div>)}</div><Button className="mt-5 h-10 rounded-[11px] font-bold" onClick={saveDays} disabled={busy}><Save className="size-4" />Save schedule</Button></section> : null}
    {tab === "holidays" ? <section className="space-y-4"><form onSubmit={addHoliday} className="grid gap-3 rounded-[18px] bg-card p-5 shadow-[var(--shadow-card)] ring-1 ring-border sm:grid-cols-[1fr_10rem_12rem_auto] sm:items-end"><label className="space-y-2 text-xs font-bold text-strong">Holiday name<Input name="name" required placeholder="Public holiday" /></label><label className="space-y-2 text-xs font-bold text-strong">Date<Input name="date" required type="date" /></label><label className="space-y-2 text-xs font-bold text-strong">Branch<select name="branchId" className="h-8 w-full rounded-none border border-input bg-background px-2.5 text-xs"><option value="">All branches</option>{branches.map((branch) => <option key={branch.id} value={branch.id}>{branch.name}</option>)}</select></label><Button type="submit" className="h-8 rounded-[9px] font-bold" disabled={busy}><Plus className="size-4" />Add</Button></form><div className="divide-y divide-border rounded-[18px] bg-card px-5 shadow-[var(--shadow-card)] ring-1 ring-border">{holidays.length ? holidays.map((holiday) => <div key={holiday.id} className="flex items-center justify-between gap-3 py-4"><div><p className="text-sm font-semibold text-strong">{holiday.name}</p><p className="text-xs text-muted-foreground">{holiday.holidayDate}{holiday.branchId ? " · Branch holiday" : " · All branches"}</p></div><Button variant="ghost" size="icon" aria-label={`Remove ${holiday.name}`} onClick={() => deleteHoliday(holiday.id)} disabled={busy}><Trash2 className="size-4 text-destructive" /></Button></div>) : <p className="py-8 text-center text-sm text-muted-foreground">No holidays configured yet.</p>}</div></section> : null}
  </div>;
}
